### ISSUE TITLE
Inability to read from Journal when using Quick Worker trait from More Traits mod.

### ISSUE THREAD

**Issue by HamSpamMcbam** [Chuckleberry-Finn/Skill-Recovery-Journal#37]
Basically as the title says. It may be what causes the translation error to occur. Log below.

**Comment by ChuckTheSheep** [comment]
Known issue, I've not been able to replicate it on my end however. Are you using default settings for both mods?

**Comment by ChuckTheSheep** [comment]
As for the translation error - it's more of a warning and can be ignored.

**Comment by HamSpamMcbam** [comment]
> Known issue, I've not been able to replicate it on my end however. Are you using default settings for both mods?

I've started a brand new world with the Apocalypse preset to avoid using different settings for the mods. The only three mods I have active are the following: Skill recovery journal, More traits, and Necroforge (though I've had this issue since before using Necroforge for testing).

I've done a little more testing and have actually discovered that it's when quick worker is _combined_ with fast reader that this issue occurs! Default settings otherwise for both the mods and the games; I've never touched the base game's ini files or anything like that.

**Comment by ChuckTheSheep** [comment]
[ff5806d](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/commit/ff5806d5f549bbfabeadbc1058b06dfd71095569) - addresses the missing translation issue.
