### ISSUE TITLE
Mod Not Loading? console.txt

### ISSUE THREAD

**Issue by RiggitySmith** [Chuckleberry-Finn/Skill-Recovery-Journal#56]
[console.txt](https://github.com/ChuckTheSheep/Skill-Recovery-Journal/files/11171627/console.txt)

this is the part I saw that seemed to be some kind of issue:
LOG  : Lua         , 1680789615761> 0> Loading: D:/Steam/steamapps/workshop/content/108600/2503622437/mods/Skill Recovery Journal/media/lua/shared/Skill Recovery Journal EggonHIFTBPatch.lua
WARN : Lua         , 1680789615761> 0> LuaManager$GlobalObject.require> require("--EHIFTB_Init") failed

**Comment by ChuckTheSheep** [comment]
This is fine. If the mod is not loading or appearing in your game chances are you have not enabled it in the appropriate menu.

For on-going single player games you have to add the mod on the mod options under the 'more' option in the load menu.
For multi-player games it needs to be enabled in the workshop content and mods menus in the server options menu.

**Comment by RiggitySmith** [comment]
sorry, I put more info in my steam comment. but I do have it in both mods and workshop items. I have tried resubscribing to the mod as well, still doesnt seem to work. but it's loading fine in the log? Is maybe another mod overwriting it? I also don't even have the Skill Recovery Journal options in the server setup
