### ISSUE TITLE
problem with crafting "transcribe journal"

### ISSUE THREAD

**Issue by QueQuahQueh** [Chuckleberry-Finn/Skill-Recovery-Journal#70]
When in the general tab of the crafting menu, the recipe for transcribing a journal is greyed out, as if I don't have the materials or skills necessary. I have a pen and bound journal in my inventory, and the crafting menu sees this, but will not let me craft the transcribed journal. [an image of this](https://imgur.com/a/GyivDAS) This is a link to an Imgur screenshot of my game.

**Comment by Chuckleberry-Finn** [comment]
Is your character illiterate by chance?
