### ISSUE TITLE
Total Kills error after creating the journal for the second and third time

### ISSUE THREAD

**Issue by Ngoett** [Chuckleberry-Finn/Skill-Recovery-Journal#79]
Hi,
I love your mod and have been using it on my MP server for awhile, unfortunately today I encountered an error with the total zombies kill. Long story short, I created a "backup" journal in a different town while my first journal was in another, I noticed that the kills were only 1/3 of what I had (For example, 3000 kills total, first journal: 2000 kills, second journal 1000 kills). So after sometimes I got back to the first journal, discarded the second one thinking it might solve the problem, and transcribed into the first journal again, but the number of kills didn't fix it self, it stayed at 2000 kills. Then I got an idea of creating a third journal and discard the first one in hope that the problem would be fixed, well it did not go as planned and now I ended up with 0 kills in my journal without any way to fix (I tried unsub and resub to the mod, removing it from server, etc...) 
;-; Please help me
Thank you so much for your time and effort <3
[console.txt](https://github.com/user-attachments/files/16092898/console.txt)

**Comment by Chuckleberry-Finn** [comment]
I'll look into it.
