### ISSUE TITLE
File doesn't exist on the client

### ISSUE THREAD

**Issue by bamaboy2611** [Chuckleberry-Finn/Skill-Recovery-Journal#80]
I've had no issue with the game and recently we enabled the Skill Journal. It worked fine, game worked fine, etc. I came back from vacation and it won't launch the game. I get the error:

File doesn't exist on the client:
media/lua/shared/skill recovery journal eggonhiftbpatch.lua
server: C:\Users\Blackbox\Zomboid\mods\Skill Recovery Journal\media\lua\shared\Skill Recovery Journal EgoonHIFTBPatch.lua

I've done nothing to the game. The server admin says he can log into the game just fine. He said he hasn't modified anything either. I've unsubscribed and resubscribed to the mod, but it never reloaded the file.

[console.txt](https://github.com/user-attachments/files/16153856/console.txt)
![Zomboid Error](https://github.com/Chuckleberry-Finn/Skill-Recovery-Journal/assets/175171699/4ff02198-af09-4619-88d4-8be71bbeed23)

**Comment by Chuckleberry-Finn** [comment]
That file isn't included in the current version of the mod, seems like your host is using an older version of the mod - this can be done accidentally if they have modpacks installed.
