### ISSUE TITLE
Skill Recovery Journal Not Showing up in MP server

### ISSUE THREAD

**Issue by PyroBread** [Chuckleberry-Finn/Skill-Recovery-Journal#81]
Having an issue and cant fix! installed onto my server shows in install list but not craftable or shown in admin item list Viewer. i installed errormagnifyer in hopes that may fix but no luck! tried reinstalling the mod. and clearing my modlist but no luck. shows in the mod list on pause menu with no issues!

**Comment by Chuckleberry-Finn** [comment]
Please provide a console log.

**Comment by PyroBread** [comment]
[server-console.txt]
[Uploading server-console.txt…]()

**Comment by Chuckleberry-Finn** [comment]
Your console log link is to this issue.
