### ISSUE TITLE
Recovery of Passive Skills is Broken

### ISSUE THREAD

**Issue by Aldeyn** [Chuckleberry-Finn/Skill-Recovery-Journal#82]
Created a Skill Journal with a character starting with Fitness 1 and Strength 0.

Skill Journal has the following contents (which seem to be the values the old character had):
![skill journal bug 1](https://github.com/user-attachments/assets/b8a177b9-7fa2-4041-ada4-3197f38b12f5)

Regardless, a new character with Fitness 1 and Strength 0 has these skill values in the end:
![skill journal bug 2](https://github.com/user-attachments/assets/465cfaa5-cfeb-4799-b6ea-ec6a26ad5354)

While Strength seems to end up roughly where it should be, Fitness falls short by a lot... it should have ended up at almost 8.

**Comment by Aldeyn** [comment]
These are the active mods - part 1/3:
![skill journal bug 3](https://github.com/user-attachments/assets/f3d4f774-39eb-4ed6-b563-2f53b9510ea7)

part 2/3:
![skill journal bug 4](https://github.com/user-attachments/assets/d6773e93-f37d-4f57-b1d9-fda682241dc3)

part 3/3:
![skill journal bug 5](https://github.com/user-attachments/assets/0005e4b7-48a7-4d56-9631-c2774f9599e9)

These are the traits I chose - part 1/3:
![skill journal bug 6](https://github.com/user-attachments/assets/0842f5c2-a94c-463e-98e4-e6c18b234986)

part 2/3:
![skill journal bug 7](https://github.com/user-attachments/assets/d1439e67-248c-4981-8183-3838464cae28)

part 3/3:
![skill journal bug 8](https://github.com/user-attachments/assets/03b7a92e-04d0-4080-9dbe-18aad668ab62)

**Comment by Aldeyn** [comment]
Screenshot of Fitness skill with tooltip:
![skill journal bug 9](https://github.com/user-attachments/assets/2a96a8b5-899a-4e1f-b209-23188e5f08f2)

**Comment by Aldeyn** [comment]
Tooltip Fitness 7:
![skill journal bug 10](https://github.com/user-attachments/assets/0415e025-d296-4ee9-9f94-fb6e4540db80)

**Comment by Chuckleberry-Finn** [comment]
Solved. Issue related to veryunderweight/underweight traits interfering with xp gains.

**Comment by Aldeyn** [comment]
Only issue remaining is that read XP shouldn't be higher than gained XP.
